# Generated by Django 5.2 on 2025-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wetnet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="wetnet_user_permissions_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
