# Generated by Django 4.2.3 on 2025-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wetnet', '0003_user_address_user_phone_number_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, max_length=15, null=True, unique=True),
        ),
    ]
